apiVersion: v1
kind: Service
metadata:
  name: identity-postgres-rw
  labels:
    app.kubernetes.io/name: etl-identity-engine
    app.kubernetes.io/component: external-postgresql-writer
spec:
  type: ExternalName
  externalName: replace-me-postgresql-writer.example.internal
