apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etl-identity
resources:
  - ../kubernetes/namespace.yaml
  - ../kubernetes/landing-pvc.yaml
  - ../kubernetes/service-service.yaml
  - pod-disruption-budget.yaml
  - service-deployment.yaml
