apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-landing-pvc
  labels:
    app.kubernetes.io/name: etl-identity-engine
    app.kubernetes.io/component: landing-zone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
