apiVersion: v1
kind: Secret
metadata:
  name: identity-postgres-secret
  labels:
    app.kubernetes.io/name: etl-identity-engine
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_DB: identity_state
  POSTGRES_USER: etl_identity
  POSTGRES_PASSWORD: replace-me-postgres-password
