apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app.kubernetes.io/name: etl-identity-engine
    app.kubernetes.io/component: service-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: etl-identity-engine
    app.kubernetes.io/component: service-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
